name: 'CI'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true) && '0' || '1'}}
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Cache SonarQube packages
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true }}
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run tests with JaCoCo
        env:
          SPRING_RABBITMQ_HOST: rabbitmq
          MYDATA_PDP_URIS: amqp://rabbitmq:5672
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ARGS: ${{ (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true) && 'org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=my-playground-organization -Dsonar.projectKey=my-playground-organization_my-playground-repo-1' || ''}}
        run: mvn -B -U clean verify org.jacoco:jacoco-maven-plugin:report-aggregate $SONAR_ARGS --no-transfer-progress
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/surefire-reports/TEST-*.xml
          flags: unittests
          fail_ci_if_error: true
          report_type: test_results
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco-aggregate/jacoco.xml
          flags: unittests
          fail_ci_if_error: true
          report_type: coverage
